### ISSUE TITLE
Unhandled exception when DNS entry not found

### ISSUE THREAD

**Issue by adevries17** [adevries17/NetPTN#2]
```
netlookup nonexistenthostname
Unhandled exception. System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family)
   at NetNsLookup.NetLookup.Main(String[] args) in C:\dev\NetPTN\NetNsLookup\NetLookup.cs:line 9
```

**Comment by adevries17** [comment]
Fixed in #4
